### ISSUE TITLE
Not able to compile the newegg project

### ISSUE THREAD

**Issue by tarunlalwani** [stamaimer/crawler#1]
Hi,

I am trying to compile the newegg folder using qmake command the make command and I get error

'''
In file included from utility.cpp:1:0:
utility.h: In constructor ‘Utility::Utility(std::ostream&, QTextEdit_)’:
utility.h:17:5: error: uninitialized reference member ‘Utility::out_stream’ [-fpermissive]
     Utility(std::ostream& out_stream, QTextEdit_ console)
     ^
utility.h:19:26: error: use of deleted function ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’
         this->out_stream = out_stream;
                          ^
In file included from /usr/include/c++/4.8/iostream:39:0,
                 from utility.h:5,
                 from utility.cpp:1:
/usr/include/c++/4.8/ostream:58:11: note: ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from utility.h:5,
                 from utility.cpp:1:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8/streambuf:41:0,
                 from utility.h:4,
                 from utility.cpp:1:
/usr/include/c++/4.8/bits/ios_base.h:789:5: error: ‘std::ios_base& std::ios_base::operator=(const std::ios_base&)’ is private
     operator=(const ios_base&);
     ^
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from utility.h:5,
                 from utility.cpp:1:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from utility.cpp:1:0:
utility.h: In static member function ‘static void Utility::redirect()’:
utility.h:32:32: error: too few arguments to function ‘void (\* qInstallMessageHandler(QtMessageHandler))(QtMsgType, const QMessageLogContext&, const QString&)’
         qInstallMessageHandler();
                                ^
In file included from /usr/include/qt5/QtCore/qglobal.h:1037:0,
                 from /usr/include/qt5/QtGui/qwindowdefs.h:45,
                 from /usr/include/qt5/QtWidgets/qwidget.h:45,
                 from /usr/include/qt5/QtWidgets/qframe.h:45,
                 from /usr/include/qt5/QtWidgets/qabstractscrollarea.h:45,
                 from /usr/include/qt5/QtWidgets/qtextedit.h:45,
                 from /usr/include/qt5/QtWidgets/QTextEdit:1,
                 from utility.h:8,
                 from utility.cpp:1:
/usr/include/qt5/QtCore/qlogging.h:150:32: note: declared here
 Q_CORE_EXPORT QtMessageHandler qInstallMessageHandler(QtMessageHandler);
                                ^
utility.cpp: At global scope:
utility.cpp:3:1: error: prototype for ‘Utility::Utility()’ does not match any in class ‘Utility’
 Utility::Utility()
 ^
In file included from utility.cpp:1:0:
utility.h:10:7: error: candidates are: Utility::Utility(const Utility&)
 class Utility : public std::basic_streambuf<char>
       ^
utility.h:17:5: error:                 Utility::Utility(std::ostream&, QTextEdit_)
     Utility(std::ostream& out_stream, QTextEdit_ console)
     ^
make: **\* [utility.o] Error 1
'''

I am using Ubuntu 14.04 LTS and QT4. Can you please help me and let me know whats wrong?

Regards,
Tarun

**Comment by stamaimer** [comment]
I wrote `Utility` class only for redirect the output of `qDebug` to `QTextEdit`. You can remove these files and compile again.

**Comment by tarunlalwani** [comment]
Thanks that helped. But the newegg url is giving 400 bad request. Any idea ?

**Comment by stamaimer** [comment]
I also found this problem a month ago. I thought it might be the client of newegg change the request header. I have no time to fix it recently. You can download the app and check the request it sends.

**Comment by tarunlalwani** [comment]
Thanks, I was not aware that you used the App traffic to search it. Now I added the below code

`request.setHeader(QNetworkRequest::UserAgentHeader, "Newegg iPhone App / 4.4.0");` 

And it was able to load the data but the App crashes after getMenus. You compiled this against QT4 or QT5?

**Comment by stamaimer** [comment]
I compiled with QT5. Could you please give me the idea of your purpose of using the code?

**Comment by tarunlalwani** [comment]
We need to write a scraper for deals website client. So I was looking for information on newegg api and came across your code. So trying to compile and use it to see how it works and how we can utilize the same and convert to python script

**Comment by stamaimer** [comment]
Oh, There is not NewEgg API. I think it's simple to convert it to python. Python is more easy to write scraper than C++. I'm learning python now

**Comment by tarunlalwani** [comment]
Yes. Anytime a JSON endpoint means things are much more easier. Python is lovely for such work. I used to be C# person, but now mostly on python
